// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: checkin.proto, android_checkin.proto

using System.Collections.Generic;
using System.ComponentModel;
using ProtoBuf;

// ReSharper disable All

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Sharp_VAG_Deluxe_3000 {
    [ProtoContract]
    public class ChromeBuildProto : IExtensible {
        [ProtoContract]
        public enum Channel {
            [ProtoEnum(Name = @"CHANNEL_STABLE")] ChannelStable = 1,
            [ProtoEnum(Name = @"CHANNEL_BETA")] ChannelBeta = 2,
            [ProtoEnum(Name = @"CHANNEL_DEV")] ChannelDev = 3,
            [ProtoEnum(Name = @"CHANNEL_CANARY")] ChannelCanary = 4,
            [ProtoEnum(Name = @"CHANNEL_UNKNOWN")] ChannelUnknown = 5
        }

        [ProtoContract]
        public enum Platform {
            [ProtoEnum(Name = @"PLATFORM_WIN")] PlatformWin = 1,
            [ProtoEnum(Name = @"PLATFORM_MAC")] PlatformMac = 2,
            [ProtoEnum(Name = @"PLATFORM_LINUX")] PlatformLinux = 3,
            [ProtoEnum(Name = @"PLATFORM_CROS")] PlatformCros = 4,
            [ProtoEnum(Name = @"PLATFORM_IOS")] PlatformIos = 5,

            [ProtoEnum(Name = @"PLATFORM_ANDROID")]
            PlatformAndroid = 6
        }

        private Channel? __pbn__channel;
        private string __pbn__ChromeVersion;
        private IExtension __pbn__extensionData;
        private Platform? __pbn__platform;

        [ProtoMember(1)]
        [DefaultValue(Platform.PlatformWin)]
        public Platform platform {
            get => __pbn__platform ?? Platform.PlatformWin;
            set => __pbn__platform = value;
        }

        [ProtoMember(2, Name = @"chrome_version")]
        [DefaultValue("")]
        public string ChromeVersion {
            get => __pbn__ChromeVersion ?? "";
            set => __pbn__ChromeVersion = value;
        }

        [ProtoMember(3)]
        [DefaultValue(Channel.ChannelStable)]
        public Channel channel {
            get => __pbn__channel ?? Channel.ChannelStable;
            set => __pbn__channel = value;
        }

        IExtension IExtensible.GetExtensionObject(bool createIfMissing) {
            return Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }

        public bool ShouldSerializeplatform() {
            return __pbn__platform != null;
        }

        public void Resetplatform() {
            __pbn__platform = null;
        }

        public bool ShouldSerializeChromeVersion() {
            return __pbn__ChromeVersion != null;
        }

        public void ResetChromeVersion() {
            __pbn__ChromeVersion = null;
        }

        public bool ShouldSerializechannel() {
            return __pbn__channel != null;
        }

        public void Resetchannel() {
            __pbn__channel = null;
        }
    }

    [ProtoContract]
    public class AndroidCheckinProto : IExtensible {
        private string __pbn__CellOperator;
        private IExtension __pbn__extensionData;
        private long? __pbn__LastCheckinMsec;
        private string __pbn__Roaming;
        private string __pbn__SimOperator;
        private DeviceType? __pbn__Type;
        private int? __pbn__UserNumber;

        [ProtoMember(2, Name = @"last_checkin_msec")]
        public long LastCheckinMsec {
            get => __pbn__LastCheckinMsec.GetValueOrDefault();
            set => __pbn__LastCheckinMsec = value;
        }

        [ProtoMember(6, Name = @"cell_operator")]
        [DefaultValue("")]
        public string CellOperator {
            get => __pbn__CellOperator ?? "";
            set => __pbn__CellOperator = value;
        }

        [ProtoMember(7, Name = @"sim_operator")]
        [DefaultValue("")]
        public string SimOperator {
            get => __pbn__SimOperator ?? "";
            set => __pbn__SimOperator = value;
        }

        [ProtoMember(8, Name = @"roaming")]
        [DefaultValue("")]
        public string Roaming {
            get => __pbn__Roaming ?? "";
            set => __pbn__Roaming = value;
        }

        [ProtoMember(9, Name = @"user_number")]
        public int UserNumber {
            get => __pbn__UserNumber.GetValueOrDefault();
            set => __pbn__UserNumber = value;
        }

        [ProtoMember(12, Name = @"type")]
        [DefaultValue(DeviceType.DeviceAndroidOs)]
        public DeviceType Type {
            get => __pbn__Type ?? DeviceType.DeviceAndroidOs;
            set => __pbn__Type = value;
        }

        [ProtoMember(13, Name = @"chrome_build")]
        public ChromeBuildProto ChromeBuild { get; set; }

        IExtension IExtensible.GetExtensionObject(bool createIfMissing) {
            return Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }

        public bool ShouldSerializeLastCheckinMsec() {
            return __pbn__LastCheckinMsec != null;
        }

        public void ResetLastCheckinMsec() {
            __pbn__LastCheckinMsec = null;
        }

        public bool ShouldSerializeCellOperator() {
            return __pbn__CellOperator != null;
        }

        public void ResetCellOperator() {
            __pbn__CellOperator = null;
        }

        public bool ShouldSerializeSimOperator() {
            return __pbn__SimOperator != null;
        }

        public void ResetSimOperator() {
            __pbn__SimOperator = null;
        }

        public bool ShouldSerializeRoaming() {
            return __pbn__Roaming != null;
        }

        public void ResetRoaming() {
            __pbn__Roaming = null;
        }

        public bool ShouldSerializeUserNumber() {
            return __pbn__UserNumber != null;
        }

        public void ResetUserNumber() {
            __pbn__UserNumber = null;
        }

        public bool ShouldSerializeType() {
            return __pbn__Type != null;
        }

        public void ResetType() {
            __pbn__Type = null;
        }
    }

    [ProtoContract]
    public enum DeviceType {
        [ProtoEnum(Name = @"DEVICE_ANDROID_OS")]
        DeviceAndroidOs = 1,
        [ProtoEnum(Name = @"DEVICE_IOS_OS")] DeviceIosOs = 2,

        [ProtoEnum(Name = @"DEVICE_CHROME_BROWSER")]
        DeviceChromeBrowser = 3,

        [ProtoEnum(Name = @"DEVICE_CHROME_OS")]
        DeviceChromeOs = 4
    }

    [ProtoContract]
    public class GservicesSetting : IExtensible {
        private IExtension __pbn__extensionData;

        [ProtoMember(1, Name = @"name", IsRequired = true)]
        public byte[] Name { get; set; }

        [ProtoMember(2, Name = @"value", IsRequired = true)]
        public byte[] Value { get; set; }

        IExtension IExtensible.GetExtensionObject(bool createIfMissing) {
            return Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
    }

    [ProtoContract]
    public class AndroidCheckinRequest : IExtensible {
        private string __pbn__DesiredBuild;
        private string __pbn__Digest;
        private string __pbn__Esn;
        private IExtension __pbn__extensionData;
        private int? __pbn__Fragment;
        private long? __pbn__Id;
        private string __pbn__Imei;
        private string __pbn__Locale;
        private long? __pbn__LoggingId;
        private string __pbn__MarketCheckin;
        private string __pbn__Meid;
        private ulong? __pbn__SecurityToken;
        private string __pbn__SerialNumber;
        private string __pbn__TimeZone;
        private string __pbn__UserName;
        private int? __pbn__UserSerialNumber;
        private int? __pbn__Version;

        [ProtoMember(1, Name = @"imei")]
        [DefaultValue("")]
        public string Imei {
            get => __pbn__Imei ?? "";
            set => __pbn__Imei = value;
        }

        [ProtoMember(10, Name = @"meid")]
        [DefaultValue("")]
        public string Meid {
            get => __pbn__Meid ?? "";
            set => __pbn__Meid = value;
        }

        [ProtoMember(9, Name = @"mac_addr")] public List<string> MacAddrs { get; } = new List<string>();

        [ProtoMember(19, Name = @"mac_addr_type")]
        public List<string> MacAddrTypes { get; } = new List<string>();

        [ProtoMember(16, Name = @"serial_number")]
        [DefaultValue("")]
        public string SerialNumber {
            get => __pbn__SerialNumber ?? "";
            set => __pbn__SerialNumber = value;
        }

        [ProtoMember(17, Name = @"esn")]
        [DefaultValue("")]
        public string Esn {
            get => __pbn__Esn ?? "";
            set => __pbn__Esn = value;
        }

        [ProtoMember(2, Name = @"id")]
        public long Id {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }

        [ProtoMember(7, Name = @"logging_id")]
        public long LoggingId {
            get => __pbn__LoggingId.GetValueOrDefault();
            set => __pbn__LoggingId = value;
        }

        [ProtoMember(3, Name = @"digest")]
        [DefaultValue("")]
        public string Digest {
            get => __pbn__Digest ?? "";
            set => __pbn__Digest = value;
        }

        [ProtoMember(6, Name = @"locale")]
        [DefaultValue("")]
        public string Locale {
            get => __pbn__Locale ?? "";
            set => __pbn__Locale = value;
        }

        [ProtoMember(4, Name = @"checkin", IsRequired = true)]
        public AndroidCheckinProto Checkin { get; set; }

        [ProtoMember(5, Name = @"desired_build")]
        [DefaultValue("")]
        public string DesiredBuild {
            get => __pbn__DesiredBuild ?? "";
            set => __pbn__DesiredBuild = value;
        }

        [ProtoMember(8, Name = @"market_checkin")]
        [DefaultValue("")]
        public string MarketCheckin {
            get => __pbn__MarketCheckin ?? "";
            set => __pbn__MarketCheckin = value;
        }

        [ProtoMember(11, Name = @"account_cookie")]
        public List<string> AccountCookies { get; } = new List<string>();

        [ProtoMember(12, Name = @"time_zone")]
        [DefaultValue("")]
        public string TimeZone {
            get => __pbn__TimeZone ?? "";
            set => __pbn__TimeZone = value;
        }

        [ProtoMember(13, Name = @"security_token", DataFormat = DataFormat.FixedSize)]
        public ulong SecurityToken {
            get => __pbn__SecurityToken.GetValueOrDefault();
            set => __pbn__SecurityToken = value;
        }

        [ProtoMember(14, Name = @"version")]
        public int Version {
            get => __pbn__Version.GetValueOrDefault();
            set => __pbn__Version = value;
        }

        [ProtoMember(15, Name = @"ota_cert")] public List<string> OtaCerts { get; } = new List<string>();

        [ProtoMember(20, Name = @"fragment")]
        public int Fragment {
            get => __pbn__Fragment.GetValueOrDefault();
            set => __pbn__Fragment = value;
        }

        [ProtoMember(21, Name = @"user_name")]
        [DefaultValue("")]
        public string UserName {
            get => __pbn__UserName ?? "";
            set => __pbn__UserName = value;
        }

        [ProtoMember(22, Name = @"user_serial_number")]
        public int UserSerialNumber {
            get => __pbn__UserSerialNumber.GetValueOrDefault();
            set => __pbn__UserSerialNumber = value;
        }

        IExtension IExtensible.GetExtensionObject(bool createIfMissing) {
            return Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }

        public bool ShouldSerializeImei() {
            return __pbn__Imei != null;
        }

        public void ResetImei() {
            __pbn__Imei = null;
        }

        public bool ShouldSerializeMeid() {
            return __pbn__Meid != null;
        }

        public void ResetMeid() {
            __pbn__Meid = null;
        }

        public bool ShouldSerializeSerialNumber() {
            return __pbn__SerialNumber != null;
        }

        public void ResetSerialNumber() {
            __pbn__SerialNumber = null;
        }

        public bool ShouldSerializeEsn() {
            return __pbn__Esn != null;
        }

        public void ResetEsn() {
            __pbn__Esn = null;
        }

        public bool ShouldSerializeId() {
            return __pbn__Id != null;
        }

        public void ResetId() {
            __pbn__Id = null;
        }

        public bool ShouldSerializeLoggingId() {
            return __pbn__LoggingId != null;
        }

        public void ResetLoggingId() {
            __pbn__LoggingId = null;
        }

        public bool ShouldSerializeDigest() {
            return __pbn__Digest != null;
        }

        public void ResetDigest() {
            __pbn__Digest = null;
        }

        public bool ShouldSerializeLocale() {
            return __pbn__Locale != null;
        }

        public void ResetLocale() {
            __pbn__Locale = null;
        }

        public bool ShouldSerializeDesiredBuild() {
            return __pbn__DesiredBuild != null;
        }

        public void ResetDesiredBuild() {
            __pbn__DesiredBuild = null;
        }

        public bool ShouldSerializeMarketCheckin() {
            return __pbn__MarketCheckin != null;
        }

        public void ResetMarketCheckin() {
            __pbn__MarketCheckin = null;
        }

        public bool ShouldSerializeTimeZone() {
            return __pbn__TimeZone != null;
        }

        public void ResetTimeZone() {
            __pbn__TimeZone = null;
        }

        public bool ShouldSerializeSecurityToken() {
            return __pbn__SecurityToken != null;
        }

        public void ResetSecurityToken() {
            __pbn__SecurityToken = null;
        }

        public bool ShouldSerializeVersion() {
            return __pbn__Version != null;
        }

        public void ResetVersion() {
            __pbn__Version = null;
        }

        public bool ShouldSerializeFragment() {
            return __pbn__Fragment != null;
        }

        public void ResetFragment() {
            __pbn__Fragment = null;
        }

        public bool ShouldSerializeUserName() {
            return __pbn__UserName != null;
        }

        public void ResetUserName() {
            __pbn__UserName = null;
        }

        public bool ShouldSerializeUserSerialNumber() {
            return __pbn__UserSerialNumber != null;
        }

        public void ResetUserSerialNumber() {
            __pbn__UserSerialNumber = null;
        }

        public override string ToString() {
            return
                $"{nameof(Imei)}: {Imei}, {nameof(Meid)}: {Meid}, {nameof(MacAddrs)}: {MacAddrs}, {nameof(MacAddrTypes)}: {MacAddrTypes}, {nameof(SerialNumber)}: {SerialNumber}, {nameof(Esn)}: {Esn}, {nameof(Id)}: {Id}, {nameof(LoggingId)}: {LoggingId}, {nameof(Digest)}: {Digest}, {nameof(Locale)}: {Locale}, {nameof(Checkin)}: {Checkin}, {nameof(DesiredBuild)}: {DesiredBuild}, {nameof(MarketCheckin)}: {MarketCheckin}, {nameof(AccountCookies)}: {AccountCookies}, {nameof(TimeZone)}: {TimeZone}, {nameof(SecurityToken)}: {SecurityToken}, {nameof(Version)}: {Version}, {nameof(OtaCerts)}: {OtaCerts}, {nameof(Fragment)}: {Fragment}, {nameof(UserName)}: {UserName}, {nameof(UserSerialNumber)}: {UserSerialNumber}";
        }
    }

    [ProtoContract]
    public class AndroidCheckinResponse : IExtensible {
        private ulong? __pbn__AndroidId;
        private string __pbn__Digest;
        private IExtension __pbn__extensionData;
        private bool? __pbn__MarketOk;
        private ulong? __pbn__SecurityToken;
        private bool? __pbn__SettingsDiff;
        private long? __pbn__TimeMsec;
        private string __pbn__VersionInfo;

        [ProtoMember(1, Name = @"stats_ok", IsRequired = true)]
        public bool StatsOk { get; set; }

        [ProtoMember(3, Name = @"time_msec")]
        public long TimeMsec {
            get => __pbn__TimeMsec.GetValueOrDefault();
            set => __pbn__TimeMsec = value;
        }

        [ProtoMember(4, Name = @"digest")]
        [DefaultValue("")]
        public string Digest {
            get => __pbn__Digest ?? "";
            set => __pbn__Digest = value;
        }

        [ProtoMember(9, Name = @"settings_diff")]
        public bool SettingsDiff {
            get => __pbn__SettingsDiff.GetValueOrDefault();
            set => __pbn__SettingsDiff = value;
        }

        [ProtoMember(10, Name = @"delete_setting")]
        public List<string> DeleteSettings { get; } = new List<string>();

        [ProtoMember(5, Name = @"setting")]
        public List<GservicesSetting> Settings { get; } = new List<GservicesSetting>();

        [ProtoMember(6, Name = @"market_ok")]
        public bool MarketOk {
            get => __pbn__MarketOk.GetValueOrDefault();
            set => __pbn__MarketOk = value;
        }

        [ProtoMember(7, Name = @"android_id", DataFormat = DataFormat.FixedSize)]
        public ulong AndroidId {
            get => __pbn__AndroidId.GetValueOrDefault();
            set => __pbn__AndroidId = value;
        }

        [ProtoMember(8, Name = @"security_token", DataFormat = DataFormat.FixedSize)]
        public ulong SecurityToken {
            get => __pbn__SecurityToken.GetValueOrDefault();
            set => __pbn__SecurityToken = value;
        }

        [ProtoMember(11, Name = @"version_info")]
        [DefaultValue("")]
        public string VersionInfo {
            get => __pbn__VersionInfo ?? "";
            set => __pbn__VersionInfo = value;
        }

        IExtension IExtensible.GetExtensionObject(bool createIfMissing) {
            return Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }

        public bool ShouldSerializeTimeMsec() {
            return __pbn__TimeMsec != null;
        }

        public void ResetTimeMsec() {
            __pbn__TimeMsec = null;
        }

        public bool ShouldSerializeDigest() {
            return __pbn__Digest != null;
        }

        public void ResetDigest() {
            __pbn__Digest = null;
        }

        public bool ShouldSerializeSettingsDiff() {
            return __pbn__SettingsDiff != null;
        }

        public void ResetSettingsDiff() {
            __pbn__SettingsDiff = null;
        }

        public bool ShouldSerializeMarketOk() {
            return __pbn__MarketOk != null;
        }

        public void ResetMarketOk() {
            __pbn__MarketOk = null;
        }

        public bool ShouldSerializeAndroidId() {
            return __pbn__AndroidId != null;
        }

        public void ResetAndroidId() {
            __pbn__AndroidId = null;
        }

        public bool ShouldSerializeSecurityToken() {
            return __pbn__SecurityToken != null;
        }

        public void ResetSecurityToken() {
            __pbn__SecurityToken = null;
        }

        public bool ShouldSerializeVersionInfo() {
            return __pbn__VersionInfo != null;
        }

        public void ResetVersionInfo() {
            __pbn__VersionInfo = null;
        }
    }
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
