//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meridian.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meridian.Resources.Localization.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meridian doesn&apos;t have rights to write content in the current folder. Please restart application with administrative privilegies..
        /// </summary>
        public static string AccessDeniedErrorDescription {
            get {
                return ResourceManager.GetString("AccessDeniedErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save settings.
        /// </summary>
        public static string AccessDeniedErrorTitle {
            get {
                return ResourceManager.GetString("AccessDeniedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to play audio.
        /// </summary>
        public static string AudioFailedErrorHeaderCommon {
            get {
                return ResourceManager.GetString("AudioFailedErrorHeaderCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection and try again. Error code: 0xC00D0035.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should choose which societies will be shown in the feed.
        /// </summary>
        public static string FeedSocietiesEmpty {
            get {
                return ResourceManager.GetString("FeedSocietiesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load albums.
        /// </summary>
        public static string LoadAlbumsErrorCommon {
            get {
                return ResourceManager.GetString("LoadAlbumsErrorCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums list is empty.
        /// </summary>
        public static string LoadAlbumsErrorEmpty {
            get {
                return ResourceManager.GetString("LoadAlbumsErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load artists.
        /// </summary>
        public static string LoadArtistsErrorCommon {
            get {
                return ResourceManager.GetString("LoadArtistsErrorCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists list is empty.
        /// </summary>
        public static string LoadArtistsErrorEmpty {
            get {
                return ResourceManager.GetString("LoadArtistsErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to audio list is denied.
        /// </summary>
        public static string LoadAudiosErrorAccessDenied {
            get {
                return ResourceManager.GetString("LoadAudiosErrorAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load audios.
        /// </summary>
        public static string LoadAudiosErrorCommon {
            get {
                return ResourceManager.GetString("LoadAudiosErrorCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio list is empty.
        /// </summary>
        public static string LoadAudiosErrorEmpty {
            get {
                return ResourceManager.GetString("LoadAudiosErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load friends.
        /// </summary>
        public static string LoadFriendsErrorCommon {
            get {
                return ResourceManager.GetString("LoadFriendsErrorCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 0 friends :(.
        /// </summary>
        public static string LoadFriendsErrorEmpty {
            get {
                return ResourceManager.GetString("LoadFriendsErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform search.
        /// </summary>
        public static string LoadSearchErrorCommon {
            get {
                return ResourceManager.GetString("LoadSearchErrorCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string LoadSearchErrorEmpty {
            get {
                return ResourceManager.GetString("LoadSearchErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load societies.
        /// </summary>
        public static string LoadSocietiesErrorCommon {
            get {
                return ResourceManager.GetString("LoadSocietiesErrorCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Societies list is empty.
        /// </summary>
        public static string LoadSocietiesErrorEmpty {
            get {
                return ResourceManager.GetString("LoadSocietiesErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load subscriptions.
        /// </summary>
        public static string LoadSubscriptionsErrorCommon {
            get {
                return ResourceManager.GetString("LoadSubscriptionsErrorCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not subscribed to anyone.
        /// </summary>
        public static string LoadSubscriptionsErrorEmpty {
            get {
                return ResourceManager.GetString("LoadSubscriptionsErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign in. Check your login and password and try again..
        /// </summary>
        public static string LoginErrorInvalidClient {
            get {
                return ResourceManager.GetString("LoginErrorInvalidClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation is required. You will be redirected to validation page..
        /// </summary>
        public static string LoginErrorNeedValidation {
            get {
                return ResourceManager.GetString("LoginErrorNeedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Media Player 10 or higher is required to play music..
        /// </summary>
        public static string WmpMissingError {
            get {
                return ResourceManager.GetString("WmpMissingError", resourceCulture);
            }
        }
    }
}
