//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meridian.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meridian.Resources.Localization.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell friends.
        /// </summary>
        public static string AboutTellFriends {
            get {
                return ResourceManager.GetString("AboutTellFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to help us? Then please tell friends about Meridian..
        /// </summary>
        public static string AboutTellFriendsTitle {
            get {
                return ResourceManager.GetString("AboutTellFriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meridian is the best way to listen to music from Vkontakte..
        /// </summary>
        public static string AboutTellMessage {
            get {
                return ResourceManager.GetString("AboutTellMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string AlbumsTab {
            get {
                return ResourceManager.GetString("AlbumsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All societies.
        /// </summary>
        public static string AllSocieties {
            get {
                return ResourceManager.GetString("AllSocieties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALBUMS.
        /// </summary>
        public static string ArtistAlbums {
            get {
                return ResourceManager.GetString("ArtistAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATED ARTISTS.
        /// </summary>
        public static string ArtistRelatedArtists {
            get {
                return ResourceManager.GetString("ArtistRelatedArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ArtistShowAll {
            get {
                return ResourceManager.GetString("ArtistShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string ArtistsTab {
            get {
                return ResourceManager.GetString("ArtistsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP TRACKS.
        /// </summary>
        public static string ArtistTopTracks {
            get {
                return ResourceManager.GetString("ArtistTopTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter symbols from the picture.
        /// </summary>
        public static string CaptchaEnterSymbols {
            get {
                return ResourceManager.GetString("CaptchaEnterSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string CaptchaTitle {
            get {
                return ResourceManager.GetString("CaptchaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry but something goes wrong. We will try to fix this as soon as possible..
        /// </summary>
        public static string CommonErrorViewContent {
            get {
                return ResourceManager.GetString("CommonErrorViewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string CommonErrorViewRestart {
            get {
                return ResourceManager.GetString("CommonErrorViewRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh... something happened :(.
        /// </summary>
        public static string CommonErrorViewTitle {
            get {
                return ResourceManager.GetString("CommonErrorViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact mode.
        /// </summary>
        public static string CompactMode {
            get {
                return ResourceManager.GetString("CompactMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin on top of other windows.
        /// </summary>
        public static string CompactModePin {
            get {
                return ResourceManager.GetString("CompactModePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracklist.
        /// </summary>
        public static string CompactModeTracklist {
            get {
                return ResourceManager.GetString("CompactModeTracklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to my music.
        /// </summary>
        public static string ContextMenuAdd {
            get {
                return ResourceManager.GetString("ContextMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to album.
        /// </summary>
        public static string ContextMenuAddToAlbum {
            get {
                return ResourceManager.GetString("ContextMenuAddToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to now playing.
        /// </summary>
        public static string ContextMenuAddToNowPlaying {
            get {
                return ResourceManager.GetString("ContextMenuAddToNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy title and artist.
        /// </summary>
        public static string ContextMenuCopyInfo {
            get {
                return ResourceManager.GetString("ContextMenuCopyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to my albums.
        /// </summary>
        public static string ContextMenuCopyToMyAlbums {
            get {
                return ResourceManager.GetString("ContextMenuCopyToMyAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View lyrics.
        /// </summary>
        public static string ContextMenuLyrics {
            get {
                return ResourceManager.GetString("ContextMenuLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string ContextMenuPlay {
            get {
                return ResourceManager.GetString("ContextMenuPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play next.
        /// </summary>
        public static string ContextMenuPlayNext {
            get {
                return ResourceManager.GetString("ContextMenuPlayNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from my music.
        /// </summary>
        public static string ContextMenuRemove {
            get {
                return ResourceManager.GetString("ContextMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from now playing.
        /// </summary>
        public static string ContextMenuRemoveFromNowPlaying {
            get {
                return ResourceManager.GetString("ContextMenuRemoveFromNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ContextMenuRemoveRadio {
            get {
                return ResourceManager.GetString("ContextMenuRemoveRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more of this.
        /// </summary>
        public static string ContextMenuSearchArtist {
            get {
                return ResourceManager.GetString("ContextMenuSearchArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ContextMenuShare {
            get {
                return ResourceManager.GetString("ContextMenuShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show artist info.
        /// </summary>
        public static string ContextMenuShowArtistInfo {
            get {
                return ResourceManager.GetString("ContextMenuShowArtistInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start radio.
        /// </summary>
        public static string ContextMenuStartRadio {
            get {
                return ResourceManager.GetString("ContextMenuStartRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CreateStationAdd {
            get {
                return ResourceManager.GetString("CreateStationAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string CreateStationArtist {
            get {
                return ResourceManager.GetString("CreateStationArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit station.
        /// </summary>
        public static string CreateStationEdit {
            get {
                return ResourceManager.GetString("CreateStationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save station.
        /// </summary>
        public static string CreateStationSave {
            get {
                return ResourceManager.GetString("CreateStationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add up to 5 artists.
        /// </summary>
        public static string CreateStationSubtitle {
            get {
                return ResourceManager.GetString("CreateStationSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New station.
        /// </summary>
        public static string CreateStationTitle {
            get {
                return ResourceManager.GetString("CreateStationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string EditAlbumName {
            get {
                return ResourceManager.GetString("EditAlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New album.
        /// </summary>
        public static string EditAlbumNewTitle {
            get {
                return ResourceManager.GetString("EditAlbumNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string EditAlbumSave {
            get {
                return ResourceManager.GetString("EditAlbumSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit album.
        /// </summary>
        public static string EditAlbumTitle {
            get {
                return ResourceManager.GetString("EditAlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string EditAudioArtist {
            get {
                return ResourceManager.GetString("EditAudioArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string EditAudioLyrics {
            get {
                return ResourceManager.GetString("EditAudioLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string EditAudioName {
            get {
                return ResourceManager.GetString("EditAudioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string EditAudioSave {
            get {
                return ResourceManager.GetString("EditAudioSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit audio.
        /// </summary>
        public static string EditAudioTitle {
            get {
                return ResourceManager.GetString("EditAudioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string FavoritesTab {
            get {
                return ResourceManager.GetString("FavoritesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add society.
        /// </summary>
        public static string FeedAdd {
            get {
                return ResourceManager.GetString("FeedAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add society.
        /// </summary>
        public static string FeedAddSocietyTitle {
            get {
                return ResourceManager.GetString("FeedAddSocietyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIETIES.
        /// </summary>
        public static string FeedSocieties {
            get {
                return ResourceManager.GetString("FeedSocieties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New music from your favorite societies.
        /// </summary>
        public static string FeedSubHeader {
            get {
                return ResourceManager.GetString("FeedSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal mode.
        /// </summary>
        public static string FullMode {
            get {
                return ResourceManager.GetString("FullMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string HeaderMenuClear {
            get {
                return ResourceManager.GetString("HeaderMenuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in list.
        /// </summary>
        public static string HeaderMenuLocalSearch {
            get {
                return ResourceManager.GetString("HeaderMenuLocalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string HeaderMenuRefresh {
            get {
                return ResourceManager.GetString("HeaderMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to my music.
        /// </summary>
        public static string HeaderMenuSave {
            get {
                return ResourceManager.GetString("HeaderMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string HeaderMenuShare {
            get {
                return ResourceManager.GetString("HeaderMenuShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape mode.
        /// </summary>
        public static string LandscapeMode {
            get {
                return ResourceManager.GetString("LandscapeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LastFmLoginTitle {
            get {
                return ResourceManager.GetString("LastFmLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrobble to Last.FM.
        /// </summary>
        public static string LastFmScrobbling {
            get {
                return ResourceManager.GetString("LastFmScrobbling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to settings.
        /// </summary>
        public static string LastFmScrobblingGoSettings {
            get {
                return ResourceManager.GetString("LastFmScrobblingGoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable scrobbling you need to connect your Last.FM account in settings. Would you like to do it now?.
        /// </summary>
        public static string LastFmScrobblingMessage {
            get {
                return ResourceManager.GetString("LastFmScrobblingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.FM scrobbling.
        /// </summary>
        public static string LastFmScrobblingTitle {
            get {
                return ResourceManager.GetString("LastFmScrobblingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, we are just loading your profile.
        /// </summary>
        public static string LoginLoading {
            get {
                return ResourceManager.GetString("LoginLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string LoginLoginButton {
            get {
                return ResourceManager.GetString("LoginLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login, e-mail or phone number.
        /// </summary>
        public static string LoginLoginTitle {
            get {
                return ResourceManager.GetString("LoginLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPasswordTitle {
            get {
                return ResourceManager.GetString("LoginPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to VK? Sign Up now!.
        /// </summary>
        public static string LoginRegisterButton {
            get {
                return ResourceManager.GetString("LoginRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with VK.
        /// </summary>
        public static string LoginStartLoginButton {
            get {
                return ResourceManager.GetString("LoginStartLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start.
        /// </summary>
        public static string LoginWelcome {
            get {
                return ResourceManager.GetString("LoginWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string MainMenuCollection {
            get {
                return ResourceManager.GetString("MainMenuCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string MainMenuFeed {
            get {
                return ResourceManager.GetString("MainMenuFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string MainMenuFriends {
            get {
                return ResourceManager.GetString("MainMenuFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS PC.
        /// </summary>
        public static string MainMenuLocalTitle {
            get {
                return ResourceManager.GetString("MainMenuLocalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN.
        /// </summary>
        public static string MainMenuMainTitle {
            get {
                return ResourceManager.GetString("MainMenuMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My music.
        /// </summary>
        public static string MainMenuMyMusic {
            get {
                return ResourceManager.GetString("MainMenuMyMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing.
        /// </summary>
        public static string MainMenuNowPlaying {
            get {
                return ResourceManager.GetString("MainMenuNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEOPLE.
        /// </summary>
        public static string MainMenuPeopleTitle {
            get {
                return ResourceManager.GetString("MainMenuPeopleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string MainMenuPopular {
            get {
                return ResourceManager.GetString("MainMenuPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        public static string MainMenuRadio {
            get {
                return ResourceManager.GetString("MainMenuRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string MainMenuRecommendations {
            get {
                return ResourceManager.GetString("MainMenuRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Societies.
        /// </summary>
        public static string MainMenuSocieties {
            get {
                return ResourceManager.GetString("MainMenuSocieties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string MainMenuSubscriptions {
            get {
                return ResourceManager.GetString("MainMenuSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VK.
        /// </summary>
        public static string MainMenuVkTitle {
            get {
                return ResourceManager.GetString("MainMenuVkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cool.
        /// </summary>
        public static string MoodsCool {
            get {
                return ResourceManager.GetString("MoodsCool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dreamy.
        /// </summary>
        public static string MoodsDreamy {
            get {
                return ResourceManager.GetString("MoodsDreamy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to energy.
        /// </summary>
        public static string MoodsEnergy {
            get {
                return ResourceManager.GetString("MoodsEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to epic.
        /// </summary>
        public static string MoodsEpic {
            get {
                return ResourceManager.GetString("MoodsEpic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extreme.
        /// </summary>
        public static string MoodsExtreme {
            get {
                return ResourceManager.GetString("MoodsExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to freedom.
        /// </summary>
        public static string MoodsFreedom {
            get {
                return ResourceManager.GetString("MoodsFreedom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to happy.
        /// </summary>
        public static string MoodsHappy {
            get {
                return ResourceManager.GetString("MoodsHappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loneliness.
        /// </summary>
        public static string MoodsLoneliness {
            get {
                return ResourceManager.GetString("MoodsLoneliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night.
        /// </summary>
        public static string MoodsNight {
            get {
                return ResourceManager.GetString("MoodsNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nostalgia.
        /// </summary>
        public static string MoodsNostalgia {
            get {
                return ResourceManager.GetString("MoodsNostalgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optimism.
        /// </summary>
        public static string MoodsOptimism {
            get {
                return ResourceManager.GetString("MoodsOptimism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psychedelic.
        /// </summary>
        public static string MoodsPsychedelic {
            get {
                return ResourceManager.GetString("MoodsPsychedelic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to romantic.
        /// </summary>
        public static string MoodsRomantic {
            get {
                return ResourceManager.GetString("MoodsRomantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sad.
        /// </summary>
        public static string MoodsSad {
            get {
                return ResourceManager.GetString("MoodsSad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sexy.
        /// </summary>
        public static string MoodsSexy {
            get {
                return ResourceManager.GetString("MoodsSexy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sport.
        /// </summary>
        public static string MoodsSport {
            get {
                return ResourceManager.GetString("MoodsSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urban.
        /// </summary>
        public static string MoodsUrban {
            get {
                return ResourceManager.GetString("MoodsUrban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vintage.
        /// </summary>
        public static string MoodsVintage {
            get {
                return ResourceManager.GetString("MoodsVintage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, we are looking for music on your PC.
        /// </summary>
        public static string MusicScanDescription {
            get {
                return ResourceManager.GetString("MusicScanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for music.
        /// </summary>
        public static string MusicScanTitle {
            get {
                return ResourceManager.GetString("MusicScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALBUMS.
        /// </summary>
        public static string MyMusicAlbums {
            get {
                return ResourceManager.GetString("MyMusicAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add album.
        /// </summary>
        public static string MyMusicAlbumsAdd {
            get {
                return ResourceManager.GetString("MyMusicAlbumsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All songs.
        /// </summary>
        public static string MyMusicAllTracks {
            get {
                return ResourceManager.GetString("MyMusicAllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string MyMusicFavorites {
            get {
                return ResourceManager.GetString("MyMusicFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        public static string MyMusicNews {
            get {
                return ResourceManager.GetString("MyMusicNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wall.
        /// </summary>
        public static string MyMusicWall {
            get {
                return ResourceManager.GetString("MyMusicWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsTab {
            get {
                return ResourceManager.GetString("NewsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next track.
        /// </summary>
        public static string NextTrack {
            get {
                return ResourceManager.GetString("NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track added to now playing.
        /// </summary>
        public static string NotificationAddedToNowPlaying {
            get {
                return ResourceManager.GetString("NotificationAddedToNowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load info about artist.
        /// </summary>
        public static string NotificationArtistNotFound {
            get {
                return ResourceManager.GetString("NotificationArtistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for artist.
        /// </summary>
        public static string NotificationLookingArtist {
            get {
                return ResourceManager.GetString("NotificationLookingArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string NotificationSaved {
            get {
                return ResourceManager.GetString("NotificationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string NotificationSaving {
            get {
                return ResourceManager.GetString("NotificationSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are listening to radio. New tracks will dynamically appear here when you switch to the next track..
        /// </summary>
        public static string NowPlayingRadioHint {
            get {
                return ResourceManager.GetString("NowPlayingRadioHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Pause.
        /// </summary>
        public static string PlayPause {
            get {
                return ResourceManager.GetString("PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular music from VK.
        /// </summary>
        public static string PopularSubHeader {
            get {
                return ResourceManager.GetString("PopularSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait mode.
        /// </summary>
        public static string PortraitMode {
            get {
                return ResourceManager.GetString("PortraitMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous track.
        /// </summary>
        public static string PrevTrack {
            get {
                return ResourceManager.GetString("PrevTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create station.
        /// </summary>
        public static string RadioAddStationButton {
            get {
                return ResourceManager.GetString("RadioAddStationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATIONS.
        /// </summary>
        public static string RadioStationsTitle {
            get {
                return ResourceManager.GetString("RadioStationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stations with artists you like.
        /// </summary>
        public static string RadioSubheader {
            get {
                return ResourceManager.GetString("RadioSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENRES.
        /// </summary>
        public static string RecommendationsGenresGroup {
            get {
                return ResourceManager.GetString("RecommendationsGenresGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOODS.
        /// </summary>
        public static string RecommendationsMoodsGroup {
            get {
                return ResourceManager.GetString("RecommendationsMoodsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advanced.
        /// </summary>
        public static string RecommendationsMusicAdvanced {
            get {
                return ResourceManager.GetString("RecommendationsMusicAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string RecommendationsMusicGeneral {
            get {
                return ResourceManager.GetString("RecommendationsMusicGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUSIC.
        /// </summary>
        public static string RecommendationsMusicGroup {
            get {
                return ResourceManager.GetString("RecommendationsMusicGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover new music by artists, genres, moods and more.
        /// </summary>
        public static string RecommendationsSubHeader {
            get {
                return ResourceManager.GetString("RecommendationsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for.
        /// </summary>
        public static string SearchResultsTitle {
            get {
                return ResourceManager.GetString("SearchResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECTION.
        /// </summary>
        public static string SearchSection {
            get {
                return ResourceManager.GetString("SearchSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        public static string SearchSectionAlbums {
            get {
                return ResourceManager.GetString("SearchSectionAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        public static string SearchSectionArtists {
            get {
                return ResourceManager.GetString("SearchSectionArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks.
        /// </summary>
        public static string SearchSectionTracks {
            get {
                return ResourceManager.GetString("SearchSectionTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.FM.
        /// </summary>
        public static string SettingsAccountsLastFm {
            get {
                return ResourceManager.GetString("SettingsAccountsLastFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your Last.FM account to enable scrobbling..
        /// </summary>
        public static string SettingsAccountsLastFmDescription {
            get {
                return ResourceManager.GetString("SettingsAccountsLastFmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed as.
        /// </summary>
        public static string SettingsAccountsSignedAs {
            get {
                return ResourceManager.GetString("SettingsAccountsSignedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SettingsAccountsSignOut {
            get {
                return ResourceManager.GetString("SettingsAccountsSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VK.
        /// </summary>
        public static string SettingsAccountsVk {
            get {
                return ResourceManager.GetString("SettingsAccountsVk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Remove current track.
        /// </summary>
        public static string SettingsHotkeyAddRemove {
            get {
                return ResourceManager.GetString("SettingsHotkeyAddRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease volume.
        /// </summary>
        public static string SettingsHotkeyDecreaseVolume {
            get {
                return ResourceManager.GetString("SettingsHotkeyDecreaseVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast forward.
        /// </summary>
        public static string SettingsHotkeyFastForward {
            get {
                return ResourceManager.GetString("SettingsHotkeyFastForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase volume.
        /// </summary>
        public static string SettingsHotkeyIncreaseVolume {
            get {
                return ResourceManager.GetString("SettingsHotkeyIncreaseVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next track.
        /// </summary>
        public static string SettingsHotkeyNext {
            get {
                return ResourceManager.GetString("SettingsHotkeyNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Pause.
        /// </summary>
        public static string SettingsHotkeyPlayPause {
            get {
                return ResourceManager.GetString("SettingsHotkeyPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous track.
        /// </summary>
        public static string SettingsHotkeyPrev {
            get {
                return ResourceManager.GetString("SettingsHotkeyPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable / Disable repeat mode.
        /// </summary>
        public static string SettingsHotkeyRepeat {
            get {
                return ResourceManager.GetString("SettingsHotkeyRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind.
        /// </summary>
        public static string SettingsHotkeyRewind {
            get {
                return ResourceManager.GetString("SettingsHotkeyRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show / Hide Meridian.
        /// </summary>
        public static string SettingsHotkeyShowHide {
            get {
                return ResourceManager.GetString("SettingsHotkeyShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable / Disable shuffle mode.
        /// </summary>
        public static string SettingsHotkeyShuffle {
            get {
                return ResourceManager.GetString("SettingsHotkeyShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SettingsMenuAbout {
            get {
                return ResourceManager.GetString("SettingsMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string SettingsMenuAccounts {
            get {
                return ResourceManager.GetString("SettingsMenuAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string SettingsMenuHotkeys {
            get {
                return ResourceManager.GetString("SettingsMenuHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string SettingsMenuUI {
            get {
                return ResourceManager.GetString("SettingsMenuUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string SettingsMenuUpdates {
            get {
                return ResourceManager.GetString("SettingsMenuUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes will be applied after restart..
        /// </summary>
        public static string SettingsRestartMessage {
            get {
                return ResourceManager.GetString("SettingsRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Restart.
        /// </summary>
        public static string SettingsSaveRestart {
            get {
                return ResourceManager.GetString("SettingsSaveRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string SettingsUIAccentColor {
            get {
                return ResourceManager.GetString("SettingsUIAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist and album art.
        /// </summary>
        public static string SettingsUIBackgroundArtTitle {
            get {
                return ResourceManager.GetString("SettingsUIBackgroundArtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string SettingsUIBackgroundColor {
            get {
                return ResourceManager.GetString("SettingsUIBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache size:.
        /// </summary>
        public static string SettingsUICacheSize {
            get {
                return ResourceManager.GetString("SettingsUICacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string SettingsUIClearCache {
            get {
                return ResourceManager.GetString("SettingsUIClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download album covers.
        /// </summary>
        public static string SettingsUIDownloadAlbumArt {
            get {
                return ResourceManager.GetString("SettingsUIDownloadAlbumArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download artist art.
        /// </summary>
        public static string SettingsUIDownloadArtistArt {
            get {
                return ResourceManager.GetString("SettingsUIDownloadArtistArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur background (reduces performance).
        /// </summary>
        public static string SettingsUIEnabledBlur {
            get {
                return ResourceManager.GetString("SettingsUIEnabledBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsUILanguage {
            get {
                return ResourceManager.GetString("SettingsUILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification when track changes.
        /// </summary>
        public static string SettingsUINotifications {
            get {
                return ResourceManager.GetString("SettingsUINotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string SettingsUINotificationsTitle {
            get {
                return ResourceManager.GetString("SettingsUINotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play using.
        /// </summary>
        public static string SettingsUIPlayUsing {
            get {
                return ResourceManager.GetString("SettingsUIPlayUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current artist image on background.
        /// </summary>
        public static string SettingsUIShowBackgroundArt {
            get {
                return ResourceManager.GetString("SettingsUIShowBackgroundArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current artist image in compact mode.
        /// </summary>
        public static string SettingsUIShowBackgroundArtCompactMode {
            get {
                return ResourceManager.GetString("SettingsUIShowBackgroundArtCompactMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icon in the tray instead of taskbar.
        /// </summary>
        public static string SettingsUIShowTrayIcon {
            get {
                return ResourceManager.GetString("SettingsUIShowTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar.
        /// </summary>
        public static string SettingsUITaskBarTitle {
            get {
                return ResourceManager.GetString("SettingsUITaskBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check now.
        /// </summary>
        public static string SettingsUpdatesCheck {
            get {
                return ResourceManager.GetString("SettingsUpdatesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check and install updates on start.
        /// </summary>
        public static string SettingsUpdatesCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsUpdatesCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test updates may contain new features and can be released more often but also can be unstable..
        /// </summary>
        public static string SettingsUpdatesDevUpdatesDescription {
            get {
                return ResourceManager.GetString("SettingsUpdatesDevUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install test updates.
        /// </summary>
        public static string SettingsUpdatesInstallDevUpdates {
            get {
                return ResourceManager.GetString("SettingsUpdatesInstallDevUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string SettingsUpdatesRestart {
            get {
                return ResourceManager.GetString("SettingsUpdatesRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meridian was updated. Restart to apply changes..
        /// </summary>
        public static string SettingsUpdatesUpdated {
            get {
                return ResourceManager.GetString("SettingsUpdatesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as society.
        /// </summary>
        public static string ShareAsSociety {
            get {
                return ResourceManager.GetString("ShareAsSociety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag tracks here to attach them to the message.
        /// </summary>
        public static string ShareBarTitle {
            get {
                return ResourceManager.GetString("ShareBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string SharePublishButton {
            get {
                return ResourceManager.GetString("SharePublishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing.
        /// </summary>
        public static string SharePublishing {
            get {
                return ResourceManager.GetString("SharePublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signed.
        /// </summary>
        public static string ShareSigned {
            get {
                return ResourceManager.GetString("ShareSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share to my wall.
        /// </summary>
        public static string ShareToMyWall {
            get {
                return ResourceManager.GetString("ShareToMyWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share with your friends and subscribers.
        /// </summary>
        public static string ShareToMyWallHint {
            get {
                return ResourceManager.GetString("ShareToMyWallHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share to society.
        /// </summary>
        public static string ShareToSociety {
            get {
                return ResourceManager.GetString("ShareToSociety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share to friend.
        /// </summary>
        public static string ShareToUserWall {
            get {
                return ResourceManager.GetString("ShareToUserWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell your friends about Meridian. This will really help us to make it better!.
        /// </summary>
        public static string TellFriendsRequestContent {
            get {
                return ResourceManager.GetString("TellFriendsRequestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell friends.
        /// </summary>
        public static string TellFriendsRequestTellButton {
            get {
                return ResourceManager.GetString("TellFriendsRequestTellButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like Meridian?.
        /// </summary>
        public static string TellFriendsRequestTitle {
            get {
                return ResourceManager.GetString("TellFriendsRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View post.
        /// </summary>
        public static string TellViewGoToPost {
            get {
                return ResourceManager.GetString("TellViewGoToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks!.
        /// </summary>
        public static string TellViewTitle {
            get {
                return ResourceManager.GetString("TellViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string TracksTab {
            get {
                return ResourceManager.GetString("TracksTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show what I&apos;m listening in my VK status.
        /// </summary>
        public static string VkStatusBroadcasting {
            get {
                return ResourceManager.GetString("VkStatusBroadcasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        public static string WallTab {
            get {
                return ResourceManager.GetString("WallTab", resourceCulture);
            }
        }
    }
}
